# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemixSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RemixSample
  pod 'Alamofire', '~> 4.7'
  pod 'Entity', :path => './Remix/Shared/Entity'
  pod 'Wireframe', :path => './Remix/Shared/Wireframe'
  pod 'GroupSelectionFeature', :path => './Remix/Shared/GroupSelectionFeature'
  pod 'Service', :path => './Remix/Shared/Service'
  pod 'Utility', :path => './Remix/Shared/Utility'

  target 'RemixSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemixSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
